targets: [http://localhost:8022, http://localhost:8023]
interval: 2

routes:
  - path: /health/
    methods: [GET]
  - path: /data/
    methods: [GET]
  - path: /fail/
    methods: [POST]
  - path: /recover/
    methods: [POST]
